from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any


STEM_NAMES = ("vocals", "drums", "bass", "other")

OUTPUT_PROFILES = (
    "audiophile",
    "basshead",
    "cinema",
    "concert",
    "hyper_immersive",
    "zenith",
)

# Legacy CLI / API slugs accepted during migration
PROFILE_ALIASES: dict[str, str] = {
    "god": "zenith",
}


def resolve_profile(name: str) -> str:
    """Normalize profile slug, applying legacy aliases."""
    return PROFILE_ALIASES.get(name, name)


@dataclass
class StemPaths:
    """Paths to Demucs-separated stem WAV files."""

    vocals: Path
    drums: Path
    bass: Path
    other: Path
    source_track: str
    model: str

    def as_dict(self) -> dict[str, str]:
        return {name: str(getattr(self, name)) for name in STEM_NAMES}

    def all(self) -> list[Path]:
        return [getattr(self, name) for name in STEM_NAMES]


@dataclass
class SectionMarker:
    label: str
    start_sec: float
    end_sec: float
    energy: float


@dataclass
class SongProfile:
    """Librosa-derived analysis profile consumed by the applier and optional LLM."""

    source: str
    duration_sec: float
    sample_rate: int
    bpm: float
    genre_hint: str
    mood_hint: str
    avg_rms: float
    crest_factor: float
    sections: list[SectionMarker] = field(default_factory=list)
    energy_curve: list[float] = field(default_factory=list)
    drop_timestamps: list[float] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["sections"] = [asdict(s) for s in self.sections]
        return data


@dataclass
class StemEffectParams:
    """Per-stem DSP parameters generated by brain (rule-based or LLM)."""

    stem: str
    eq_low_hz: float = 120.0
    eq_low_db: float = 0.0
    eq_mid_hz: float = 1200.0
    eq_mid_db: float = 0.0
    eq_high_hz: float = 8000.0
    eq_high_db: float = 0.0
    stereo_width: float = 1.0
    reverb_mix: float = 0.0
    reverb_room_size: float = 0.5
    reverb_damping: float = 0.5
    reverb_decay_sec: float = 1.5
    pan_lfo_hz: float = 0.0
    pan_depth: float = 0.0
    gain_db: float = 0.0
    center_lock: bool = False
    compressor_enabled: bool = True
    comp_threshold_db: float = -18.0
    comp_ratio: float = 2.5
    comp_attack_ms: float = 5.0
    comp_release_ms: float = 80.0
    # Kinetic Engine — static values above are peaks/fallbacks
    width_envelope: list[tuple[float, float]] | None = None
    reverb_mix_envelope: list[tuple[float, float]] | None = None
    pan_depth_envelope: list[tuple[float, float]] | None = None
    # Micro-detail recovery (tone board)
    tape_drive_db: float = 0.0
    transient_shaping: bool = False
    transient_threshold_db: float = -15.0
    transient_ratio: float = 4.0
    transient_attack_ms: float = 30.0
    transient_release_ms: float = 50.0
    vocal_air_db: float = 0.0
    vocal_air_hz: float = 8500.0
    # Elliptical M/S filter — HPF on Side channel (0 = disabled)
    elliptical_side_hpf_hz: float = 0.0

    def has_automation(self) -> bool:
        return bool(self.width_envelope or self.reverb_mix_envelope or self.pan_depth_envelope)


@dataclass
class RenderPlan:
    """Full effect plan for all stems at a given output profile."""

    profile_name: str
    stem_params: dict[str, StemEffectParams]
    master_gain_db: float = 0.0
    master_glue_threshold_db: float = -1.0
    master_lufs_target: float = -14.0
    master_true_peak_db: float = -0.1
    # Legacy alias consumed by older render plans on disk
    master_limiter_db: float = -1.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "profile_name": self.profile_name,
            "master_gain_db": self.master_gain_db,
            "master_glue_threshold_db": self.master_glue_threshold_db,
            "master_lufs_target": self.master_lufs_target,
            "master_true_peak_db": self.master_true_peak_db,
            "stem_params": {k: asdict(v) for k, v in self.stem_params.items()},
        }


@dataclass
class PipelineResult:
    input_path: Path
    output_path: Path
    stems: StemPaths
    profile: SongProfile
    plan: RenderPlan
    work_dir: Path
